version: '3.8'

services:
  app:
    image: serversideup/php:8.4-fpm
    container_name: php-app
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  web:
    image: nginx:stable
    container_name: nginx-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge